export const config = { amp: true };
export * from "./PostCard";
export * from "./Footer";
export * from "./Meta";
export * from "./PostHeader";
export * from "./PostBody";
export * from "./AuthorIntroduce";
export * from "./NavMenu";
export * from "./Header";
export * from "./AboutHeader";
